// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestFulApi.Data;

namespace RestFulApi.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230310024238_AddOrderBillSchema")]
    partial class AddOrderBillSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RestFulApi.Data.Category", b =>
                {
                    b.Property<int>("CategoryCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryCode");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("RestFulApi.Data.DetailOrderBill", b =>
                {
                    b.Property<Guid>("OrderCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderCode", "ProductCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("DetailOrderBill");
                });

            modelBuilder.Entity("RestFulApi.Data.OrderBill", b =>
                {
                    b.Property<Guid>("OrderCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrderCode");

                    b.ToTable("OrderBill");
                });

            modelBuilder.Entity("RestFulApi.Data.Products", b =>
                {
                    b.Property<Guid>("ProductCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoryCode")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ProductDiscount")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductCode");

                    b.HasIndex("CategoryCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RestFulApi.Data.DetailOrderBill", b =>
                {
                    b.HasOne("RestFulApi.Data.OrderBill", "OrderBill")
                        .WithMany("DetailOrderBills")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK_DetailOrderBill_Order")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestFulApi.Data.Products", "Products")
                        .WithMany("DetailOrderBills")
                        .HasForeignKey("ProductCode")
                        .HasConstraintName("FK_DetailOrderBill_Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderBill");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestFulApi.Data.Products", b =>
                {
                    b.HasOne("RestFulApi.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryCode");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestFulApi.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestFulApi.Data.OrderBill", b =>
                {
                    b.Navigation("DetailOrderBills");
                });

            modelBuilder.Entity("RestFulApi.Data.Products", b =>
                {
                    b.Navigation("DetailOrderBills");
                });
#pragma warning restore 612, 618
        }
    }
}
